name: "Make Release"
description: 'Performs build and prepares for release'
inputs:
  version:
    description: 'Release version'
    required: true


runs:
  using: "composite"
  steps:
    - name: 🤖 Excavate
      run: |
        for file in bucket/*.json
        do
          python bin/generate.py "$file" --version "${{ inputs.version }}"
        done
      shell: bash

    - name: 📦 Create Archive
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          "C:/Program Files/7-Zip/7z.exe" a -mfb=258 -tzip "context-actions-${{ inputs.version }}.zip"  actions dist bucket *.bat
        else
          zip -r -9 -y -m "context-actions-${{ inputs.version }}.zip" actions dist bucket *.bat
        fi
      shell: bash

    - name: ✅ Create Draft Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.version }}
        name: Release ${{ inputs.version }}
        draft: true
        prerelease: false
        generate_release_notes: true
        files: |
          ./context-actions-${{ inputs.version }}.zip
