name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version (e.g., v1.0.0)"
        required: true
      remove_if_existing:
        description: "Remove tag if it already exists"
        required: true
        default: false
        type: boolean
jobs:
  create-and-push-tag:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create and Push Tag
        run: |
          if git rev-parse --quiet --verify "${{ github.event.inputs.version }}"; then
          if [ "${{ github.event.inputs.remove_if_existing }}" = "true" ]; then
          echo "Tag exists, removing..."
          git tag -d ${{ github.event.inputs.version }}
          git push --delete origin ${{ github.event.inputs.version }}
          else
          echo "Tag already exists. Exiting..."
          exit 1
              fi
          fi
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Release Process Workflow
        uses: ./.github/workflows/release-process.yml
        with:
          version: ${{ github.event.inputs.version }}
